rgsystemes/lib-ui

package.json

~Wait for #23 before merging this one~

[REVIEW] Bump version

---

src/Atoms/Button/Button.jsx
src/Atoms/Input/Input.jsx

https://github.com/rgsystemes/kb/issues/4423

[REVIEW] Adjust medium Input & Button height

---

src/Atoms/Button/Button.jsx

https://github.com/rgsystemes/kb/issues/4423

[REVIEW] Add spaces to material button label

---

src/Molecules/ExpansionPanel/ExpansionPanel.stories.jsx

Replace: https://github.com/rgsystemes/lib-ui/pull/29
Issue: https://github.com/rgsystemes/kb/issues/4423

[REVIEW] fix: line-height and cursor in story

---

src/Atoms/Banner/Banner.jsx

https://github.com/rgsystemes/kb/issues/4482

Pass down props to the Container native element in Banner

---

src/Atoms/Popover/Popover.jsx
src/Molecules/TableList/Row/Row.jsx
src/Organisms/EnhancedList/EditColumns/ColumnGroup/ColumnGroup.jsx

https://github.com/rgsystemes/kb/issues/4613#issuecomment-588888802

Enhance list test feedback fixes 2

---

package-lock.json
package.json
src/Molecules/List/ListItemIcon/ListItemIcon.jsx
src/Molecules/TableList/SortedColumn/SortedColumn.jsx

https://github.com/rgsystemes/kb/issues/4613

Fix enhanced list ui

---

package-lock.json
package.json
src/Molecules/TableList/Row/Row.jsx
src/Molecules/TableList/TableList.jsx
src/Molecules/TableList/TableList.stories.jsx
src/Molecules/TableList/TableList.test.js

https://github.com/rgsystemes/kb/issues/4778

Handle multiple selection on TableList

---

src/Molecules/Filter/Filter.jsx
src/Molecules/Filter/Filter.test.jsx
src/Molecules/TableList/SortedColumn/SortedColumn.jsx
src/Molecules/TableList/SortedColumn/SortedColumn.test.jsx

https://github.com/rgsystemes/kb/issues/4779

[REVIEW] - Filter on enter and on check button

---

package-lock.json
package.json
src/Organisms/EnhancedList/EditColumns/ColumnGroup/ColumnGroup.jsx
src/Organisms/EnhancedList/EditColumns/EditColumns.jsx

https://github.com/rgsystemes/kb/issues/4779

[REVIEW] Fix disabling columns

---

package-lock.json
src/Molecules/DateRange/DateRange.jsx
src/Molecules/Export/Export.jsx

https://github.com/rgsystemes/kb/issues/4740

Export actions minor fix & DateRange flex direction

---

.storybook/locales/en.js
src/Molecules/Filter/Filter.jsx
src/Molecules/Filter/Filter.test.jsx
src/Organisms/EnhancedList/EnhancedList.stories.jsx

https://github.com/rgsystemes/kb/issues/4779

[REVIEW] Doc story

---

.storybook/locales/en.js
src/Molecules/DateRange/DateRange.jsx
src/Molecules/Filter/Filter.jsx
src/Molecules/Filter/Filter.test.jsx
src/Molecules/Filter/constants.js

https://github.com/rgsystemes/kb/issues/4841

Filters clearing & DateRange fixes

---

src/Molecules/Editable/Editable.stories.jsx
src/Molecules/FormControl/FormControl.jsx

https://github.com/rgsystemes/kb/issues/4843

Add margin-top to all label direct children

---

src/Molecules/ActionCard/ActionCard.stories.jsx

https://github.com/rgsystemes/kb/issues/4835

[REVIEW] Add placeholder on inputs in ActionCard

---

PULL_REQUEST_TEMPLATE.md

Use Draft PR instead (https://github.blog/2019-02-14-introducing-draft-pull-requests/)

chore: add PR template

---

src/Molecules/ActionCard/ActionCard.stories.jsx

https://github.com/rgsystemes/kb/issues/4835

[REVIEW] Do not autofocus any input

---

src/Molecules/Header/Header.stories.jsx
src/Molecules/Header/InputSaveProgress/InputSaveProgress.jsx

Fix Header Molecule

---

src/Atoms/ButtonNoBorder/ButtonNoBorder.jsx
src/Templates/Fullscreen/Fullscreen.jsx
src/Templates/Fullscreen/Fullscreen.test.jsx

https://github.com/rgsystemes/kb/issues/4878

Fullscreen fixes

---

package-lock.json
package.json

https://github.com/testing-library/dom-testing-library/commit/a98dc9f2052bcaa36932a16e27698b047af761fd

chore(deps): upgrade @testing-library/react

---

src/Atoms/Banner/Banner.jsx

Fix Header Page Side effect

---

src/Templates/Fullscreen/Fullscreen.jsx
src/Templates/Fullscreen/Fullscreen.stories.jsx

Improve Fullscreen Component Layout
